// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADyBeiKgUOoUnYgk_QJHyjyK_4TYtrq70',
    appId: '1:406727162314:web:072caa736b535b90097733',
    messagingSenderId: '406727162314',
    projectId: 'starfleet-f90ad',
    authDomain: 'starfleet-f90ad.firebaseapp.com',
    storageBucket: 'starfleet-f90ad.appspot.com',
    measurementId: 'G-BS9J8QW1N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhrbhumZg_LEDmPysKa3pyBMuBpzlKveM',
    appId: '1:406727162314:android:98aefab1f4c502a3097733',
    messagingSenderId: '406727162314',
    projectId: 'starfleet-f90ad',
    storageBucket: 'starfleet-f90ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_QeI9zLOt5Wex1wwcNUxRyKB-EGedGsE',
    appId: '1:406727162314:ios:99d5546b9acb7548097733',
    messagingSenderId: '406727162314',
    projectId: 'starfleet-f90ad',
    storageBucket: 'starfleet-f90ad.appspot.com',
    iosClientId: '406727162314-vsjimr8sfvbkug3luuhc7mvnqbdnprvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.starfleetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_QeI9zLOt5Wex1wwcNUxRyKB-EGedGsE',
    appId: '1:406727162314:ios:99d5546b9acb7548097733',
    messagingSenderId: '406727162314',
    projectId: 'starfleet-f90ad',
    storageBucket: 'starfleet-f90ad.appspot.com',
    iosClientId: '406727162314-vsjimr8sfvbkug3luuhc7mvnqbdnprvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.starfleetApp',
  );
}
